# Terraform Apply
version: 0.1
phases:
  pre_build:
    commands:
      - terraform init
      - terraform validate

  build:
    commands:
      - cd #{PipelineVariables.ACCOUNT_ID}
      - terraform apply -auto-approve
